### ISSUE TITLE
Please write in README and Wiki what the plugin does or plans to do. I currently have no idea and have clicked on every link.

### ISSUE THREAD

**Issue by weselben** [Syrent/EnhancedVelocity#11]
It would be nice to see what the plugin actually does in your README file. :) :)

Edit: More of what it's trying to do, I can piece it together from the command list but, I think you understand what I mean ;)

**Comment by kitt-schlatter** [comment]
I can echo this sentiment, too. I still don't understand fully what the purpose of this plugin is - is it just to add some helpful commands? Or, does it implement some kind of performance improvements that players might actually notice?

**Comment by Syrent** [comment]
I've updated the README with an added a new `What is it?` section. EnhancedVelocity primarily adds a few commands like `/glist` and `/find`. It doesn't involve any complex features or performance-related enhancements.
