### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by SalmonSnakeD** [Syrent/EnhancedVelocity#5]
I was wondering that could you add '/send' and '/alert' command to this plugin? Velocitytools has thoose commands, but this plugin doesn't. 
(I couldn't find a place where I could put reviews/sugegstions, so I posted here.)

**Comment by Syrent** [comment]
Thanks for the suggestions.
I'll add them as soon as i can.

**Comment by Syrent** [comment]
Added in version 1.2.0
Download link: https://github.com/Syrent/EnhancedVelocity/releases/tag/v1.2.0

**Comment by SalmonSnakeD** [comment]
Thank you very much!
